---
# tasks file for buildsite

- name: Install prereqs to clone packages
  package:
    name:
      - git
      - python-pip
      - podman
    state: present
  become: yes

- name: Pull down checky into a local working directory
  git:
    repo: https://github.com/rufuskd/checky.git
    dest: ../checkycode
    force: yes

- name: Pip install npm to pull angular
  command: 'pip install npm'

- name: Install angular utils locally to the checky code
  command: 'npm install'
  args:
    chdir: ../checkycode/
  become: yes

- name: Install angular cli locally to the checky code
  command: 'npm install -g @angular/cli'
  args:
    chdir: ../checkycode/
  become: yes

- name: Build the angular site
  command: ./node_modules/.bin/ng build --prod
  args:
    chdir: ../checkycode/
  tags:
  - rebuild

- name: Move the built site to the nginx container folder
  copy:
    src: ../checkycode/dist/
    dest: ../checkycontainer/
  tags:
  - rebuild

- name: Cleanup previously used IP info
  file:
    path:
      - "/var/lib/cni/networks/podman/{{ nginx.ip }}"
      - "/var/lib/cni/networks/podman/{{ mongo.ip }}"
      - "/var/lib/cni/networks/podman/{{ gunicorn.ip }}"
      - "/var/lib/cni/networks/podman/last_reserved_ip.0"
      - "/var/lib/cni/networks/podman/lock"
    state: absent
  tags:
  - rebuild
  become: yes
