---
# tasks file for buildsite

- name: Install all prerequisite packages
  import_tasks: 01-prerequisites.yml
  tags:
    - pullCode
    - useLocal

- name: If doing remote pull build, pull Checky code
  import_tasks: 02-pullGit.yml
  tags: pullCode

- name: If doing local build, use locally stored Checky code as per group_vars
  import_tasks: 02-pullLocal.yml
  tags: useLocal

- name: Build the site using the code we have chosen
  import_tasks: 03-build.yml
  tags:
    - pullCode
    - useLocal
