---
# tasks file for buildsite

- name: Install prereqs to clone packages
  package:
    name:
      - git
      - python-pip
    state: present
  become: yes

- name: Pull down checky into a local working directory
  git:
    repo: https://github.com/rufuskd/checky.git
    dest: ../checkycode

- name: Pip install npm to pull angular
  command: 'pip install npm'

- name: Install angular utils locally to the checky code
  command: 'npm install'
  args:
    chdir: ../checkycode/
  become: yes

- name: Install angular cli locally to the checky code
  command: 'npm install -g @angular/cli'
  args:
    chdir: ../checkycode/
  become: yes
