---
- hosts: localhost
  tasks:
    - import_role:
        name: buildsite
      tags:
      - frontend
    - import_role:
        name: nginx
      tags:
      - frontend
      - rebuild
    - import_role:
        name: mongo
      tags:
      - nofrontend
      - rebuild
    - import_role:
        name: gunicorn
      tags:
      - nofrontend
      - rebuild
