---
- hosts: localhost
  tasks:
    - import_role:
        name: buildsite
    - import_role:
        name: nginx
      tags:
        - useLocal
        - pullCode
    - import_role:
        name: mongo
      tags:
        - useLocal
        - pullCode
    - import_role:
        name: gunicorn
      tags:
        - useLocal
        - pullCode
