---
# tasks file for nginx

- name: Stop any existing nginx container
  command: podman stop checky-nginx
  ignore_errors: yes
  become: yes
  tags: cleanup

- name: Remove any existing nginx container
  command: podman rm checky-nginx
  ignore_errors: yes
  become: yes
  tags: cleanup

- name: Build the nginx container
  podman_image:
    name: checky-nginx
    path: ../checkycontainer/
    build:
      format: docker
    force: yes
  become: yes

- name: Run the nginx container
  command: podman run --name checky-nginx -p 80:80 --ip={{ nginx.ip }} -d checky-nginx
  become: yes
